blank_issues_enabled: false

contact_links:
  - name: BlackForest proposals
    url: https://github.com/godotengine/godot-proposals
    about: Please submit feature proposals on the BlackForest proposals repository, not here.

  - name: BlackForest documentation repository
    url: https://github.com/godotengine/godot-docs
    about: Please report issues with documentation on the BlackForest documentation repository, not here.

  - name: BlackForest community channels
    url: https://blackforestengine.org/community
    about: Please ask for technical support on one of the other community channels, not here.
