name: Build blackforest-cpp
description: Build blackforest-cpp with the provided options.

inputs:
  bin:
    description: Path to the BlackForest binary.
    required: true
    type: string
  scons-flags:
    description: Additional SCons flags.
    type: string
  scons-cache:
    description: The SCons cache path.
    default: ${{ github.workspace }}/.scons_cache/
    type: string
  blackforest-cpp-branch:
    description: The blackforest-cpp branch.
    default: master
    type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
        repository: godotengine/blackforest-cpp
        ref: ${{ inputs.godot-cpp-branch }}
        path: blackforest-cpp

    - name: Extract API
      shell: sh
      run: ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api

    - name: SCons Build
      shell: sh
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
      run: scons --directory=./blackforest-cpp/test "gdextension_dir=${{ github.workspace }}" ${{ inputs.scons-flags }}
